### ISSUE TITLE
Stored XSS vulnerability

### ISSUE THREAD

**Issue by sebastianhofmannlegal** [mosaic-hgw/gICS#2]
Using the editor fields, for example when creating consent documents, it is possible to insert code that is not properly escaped.

The following payload is executed as soon as a consent document is loaded:

```
<img src="x" onerror="javascript:alert('XSS')">
```

<img width="1030" alt="Bildschirm­foto 2022-12-30 um 11 31 12" src="https://user-images.githubusercontent.com/76694226/210060660-0cc61c89-8161-4b2c-b53f-800f492d716a.png">
<img width="1079" alt="Bildschirm­foto 2022-12-30 um 11 31 57" src="https://user-images.githubusercontent.com/76694226/210060729-836c56df-6c3b-48f8-88bb-3869e8470c9f.png">
<img width="1221" alt="Bildschirm­foto 2022-12-30 um 11 32 42" src="https://user-images.githubusercontent.com/76694226/210060791-44d18d85-79cf-40f4-a741-cf2a633bae31.png">

**Comment by sebastianhofmannlegal** [comment]
This payload also works pretty well:

`<style>@keyframes x{}</style><xss style="animation-name:x" onanimationend="alert(1)"></xss>`

**Comment by mosaic-hgw** [comment]
Thanks for your detailed feedback. We added a respective ticket and will fix this issue in an upcoming update.

**Comment by mosaic-hgw** [comment]
Fixed in upcoming gICS Version 2023.1.0. Expected release date 2023-04-30.
