### ISSUE TITLE
NullPointerException caused by missing entry in qc table

### ISSUE THREAD

**Issue by philwinn** [mosaic-hgw/gICS#3]
gICS (version 2.14.1) fails to start due to a `NullPointerException` thrown from `ConsentCache.init()`:
```
Caused by: java.lang.NullPointerException
        at deployment.gics-2.14.1.ear.org.emau.icmvc.ganimed.ttp-cm2-ejb-2.14.1.jar//org.emau.icmvc.ganimed.ttp.cm2.internal.ConsentCache.init(ConsentCache.java:152)
        at deployment.gics-2.14.1.ear.org.emau.icmvc.ganimed.ttp-cm2-ejb-2.14.1.jar//org.emau.icmvc.ganimed.ttp.cm2.DAO.checkConsentCache(DAO.java:257)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
Within `ConsentCache`, `consent.getQc().isQcPassed()` seems to be the cause of the Exception. Checking the database tables `consent` and `qc` reveals that the count for `qc` is one less than the count for `consent`, i.e. the expected `qc` entry for the most recent entry in `consent` does not exist for unknown reason. With this unequal counts in mind, it makes sense that, for this most recent consent, `consent.getQc()` returns `NULL` due to the missing entry in the `qc` table, thereby causing the NPE.

**Comment by mosaic-hgw** [comment]
This affects the gICS versions < 2023.1.0.

The missing QC entry here results in incorrect blocking. This was fixed as part of the renovated gICS cache in version 2023.1.0 

Existing gICS databases can also be fixed independently of a software update with the following SQL snippet.

The **default_qc_state** can and should be modified before execution, for example '**not_checked**'.

```
-- please modify default_qs_state e.g. 'not_checked'
SET @default_qs_state := '###auto_generated###';

INSERT INTO qc (CONSENT_DATE, VIRTUAL_PERSON_ID, CT_DOMAIN_NAME, CT_NAME, CT_VERSION, TIMESTAMP, TYPE, COMMENT)
SELECT CONSENT_DATE, VIRTUAL_PERSON_ID, CT_DOMAIN_NAME, CT_NAME, CT_VERSION, NOW(), @default_qs_state, 'initial qs entry gics version 2.12.0'
FROM consent c
WHERE (c.CONSENT_DATE, c.VIRTUAL_PERSON_ID, c.CT_DOMAIN_NAME, c.CT_NAME, c.CT_VERSION) NOT IN (SELECT CONSENT_DATE, VIRTUAL_PERSON_ID, CT_DOMAIN_NAME, CT_NAME, CT_VERSION  FROM qc);
INSERT INTO qc_hist (CONSENT_DATE, VIRTUAL_PERSON_ID, CT_DOMAIN_NAME, CT_NAME, CT_VERSION, TIMESTAMP, TYPE, COMMENT, START_DATE)
SELECT CONSENT_DATE, VIRTUAL_PERSON_ID, CT_DOMAIN_NAME, CT_NAME, CT_VERSION, NOW(), @default_qs_state, 'initial qs entry gics version 2.12.0', NOW()
FROM consent c
WHERE (c.CONSENT_DATE, c.VIRTUAL_PERSON_ID, c.CT_DOMAIN_NAME, c.CT_NAME, c.CT_VERSION) NOT IN (SELECT CONSENT_DATE, VIRTUAL_PERSON_ID, CT_DOMAIN_NAME, CT_NAME, CT_VERSION  FROM qc_hist);

```

The new gICS version 2023.1.0 will be released at the beginning of May 2023.
